name: ESLint
on:
  push:
    branches-ignore:
      - bump-version
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'package-lock.json'
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
